version: 0.2
​phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean install
  post_build:
    commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - target/app.jar